version: '3.7'
services:
    wiremock:
        image: rodolpheche/wiremock:2.26.3-alpine
        ports: 
            - 8080:8080
        volumes: 
            - ./stubs:/home/wiremock
        command: --verbose
