.ONESHELL:

SHELL := /bin/bash
.SHELLFLAGS := -ec
.DEFAULT_GOAL := test

format: ## Fixes format errors by applying the canonical Go style
	gofmt -d -s -w pkg

linter:
	golangci-lint run ./...

run-test:
	docker-compose up -d
	go test -gcflags '-N -l' -cover -v -race -p 1 ./...
	docker-compose down

test: generate run-test ## Run all test suite

generate: ## Generate all autogenerated files
	go generate ./...